project:
  type: website
  render: 
    - "*.qmd"
    - "!*_.qmd"
  preview: 
    port: 8888
website:
  title: Shane
  open-graph: true
  favicon: image/favicon.ico
  page-navigation: true
  navbar:
    title: false
    logo: image/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  draft-mode: visible
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Pretendard Variable
    monofont: JetBrains Mono
    include-in-header: header.html
    
