---
title: Initial Steps in Entrepreneurship
subtitle: Convertible bond
description: ""
author: Shane Oh
date: 2023-08-21
categories:
  - Finance
  - Entrepreneurship
---

## 자산 = 자본 + 부채
이 항등식은 재무상태표의 대전제이다. 회계 등식이라고 한다. 

**자산(Asset)**은 기업이 소유하고 있는 모든 경제적 가치이다(예: 현금, 재고, 부동산 등).
이 중 **부채(Liability)**는 타인의 몫으로, 기업이 외부로부터 빌린 자금이나 갚아야할 의무에 해당된다(예: 대출, 미지급금 등).
**자본(Equity)**은 자산에서 부채를 제외한 나머지를 칭한다.

## 꾸짖을 책(責)과 빚 채(債)
이번 포스팅은 부채에 관한 내용이므로 '채'자가 무엇인지 알아보자.

꾸짖을 책(責)의 어원은 가시(龶=朿)가 돋친 돈(貝). 즉, 빚을 뜻한다[^꾸짖을책].
責자를 꾸짓다는 뜻으로 쓰이면서 빚은 인변(亻)을 붙여 債자를 쓴다[^빚채].
責은 책임(責任), 책무(責務) 등으로 쓰인다.

직책을 달고 있다는 것은 꾸중을 도맡으면서 돈 값을 하라는 자리인 것인가ㅎㅎ.

[^꾸짖을책]: [위키낱말사전, 꾸짖을 책(責)](https://ko.wiktionary.org/wiki/責)
[^빚채]: [위키낱말사전, 빚 채(債)](https://ko.wiktionary.org/wiki/債)

## 전환사채(Convertible Bond, CB)
전환사채는 일반적으로 주식회사가 투자자에게 발행하는 하나의 금융 상품이다.
해당 상품에는 발행 회사와 투자자간 중요한 계약 조건이 있는데 이것이 [콜옵션과 풋옵션](#call-put-option)이다.

```{mermaid}
%%| layout-align: center
flowchart LR
A(주식회사) -- 전환사채증권 --> B(투자자)
B -- 납입 --> A
```

이로서 납입금은 회사의 자산으로 인식된다.

## 전환사채의 콜옵션과 풋옵션 {#call-put-option}

전환사채증권의 단위는 일반적으로 금액(예: 원, 달러 등)이다. 문서의 주요 구성 요소는 다음과 같다.

- 발행 금액: 전환사채의 액면 금액을 명시한다.
- 이자율: 예를 들어 5% 등
- 만기일: 전환사채의 만기일을 명시한다. 만기일에 도달하면 사채권자(투자자)가 채권을 주식으로 전환할지 아니면 원금을 상환받을지 결정한다.
- 전환가액: 전환사채를 주식으로 전환할 때 적용하는 주식 가격이다.
- 부가조건

부가조건들 중에 콜옵션과 풋옵션이 들어간다. 각각 발행한 회사 그리고 사채권자의 조기상환권이다.
