---
title: Initial Steps in Entrepreneurship
subtitle: Capital contribution
description: ""
author: Shane Oh
date: 2023-08-21
categories:
  - Finance
  - Entrepreneurship
---

3명의 창업자가 함께 프로젝트를 진행하다가 이를 정식으로 회사로 발전시키기로 결정했다.
이들은 법인을 설립하여 프로젝트를 회사로 전환하기로 한다.

## 법인 설립 준비
- 상호 및 사업 목적 결정
  - 회사의 상호와 사업 목적을 결정한다.

- 정관 작성
  - 회사의 **정관**을 작성한다. 정관은 회사의 기본 규칙을 담고 있으며, 자본금, 주식, 회사 운영 방식 등을 포함한다.

## 은행에 자본금 납입
- 자본금 납입을 위한 은행 계좌 개설
  - 법인을 설립하기 전 은행에서 발기인 명의의 임시 계좌를 개설한다. 발기인은 회사 설립을 주도하는 사람들로, 이 경우 3명의 창업자가 발기인이 된다.
  - 임시 계좌는 법인 설립을 위해 자본금을 입금하고 증빙하기 위한 용도로 사용된다.

- 자본금 입금
  - 각 발기자는 자본금으로 출자하기로 한 금액을 **임시 계좌**에 입금한다.
  예를 들어, 각각 333만 3천원씩 입금하여 총 1,000만원을 마련한다.
  - 이 과정에서 은행은 자본금이 제대로 입금되었는지 확인하고, 이를 증명하기 위한 **자본금 납입증명서**를 발급할 수 있다.

## 법인 설립 등기
- 설립 등기 신청
  - 은행에서 받은 **자본금 납입증명서**, **정관** 및 발기인들이 작성한 서류 등을 준비하여 관할 등기소에 제출한다.
  - 이때 설립 등기 신청서에는 회사의 기본 정보(상호, 사업 목적, 주소 등)와 자본금 납입 내역, 주식 발행 내역 등이 포함된다.

- 법인 설립 완료
  - 등기소에서 서류 검토 후 문제가 없을 경우 법인 설립이 완료된다.
  - 설립 등기가 완료되면 법인이 공식적으로 설립된 것이며, 회사가 법적으로 존재하게 된다.

## 법인 계좌로 자본금 이체
- 법인 명의의 계좌 개설
  - 설립 등기 완료 후, 법인 명의의 정식 계좌를 은행에 개설한다.
  - 임시 계좌에 있던 자본금을 해당 법인 계좌로 이체한다.

## 시업자 등록
- 사업자 등록 신청
  - 법인 설립이 완료된 후, 관할 세무서에 사업자 등록을 신청한다. 이 과정에서 법인 설립 등기부 등본, 정관, 자본금 납입증명서 등을 제출한다.
- 사업자 등록증 발급
  - 세무서에서 서류 검토 후 문제가 없을 경우 사업자 등록증을 발급받는다.
  이제야 비로서 법인으로 사업을 시작할 준비가 된다.